### ISSUE TITLE
No Clue on Mac OS Sierra

### ISSUE THREAD

**Issue by dJunkyKode** [fifthsegment/Wpress-Extractor#11]
I've tried for a long hour to use the Mac version but have no clue how to get it working.
My back up file is on: "/Users/cisco/Desktop/e"

So am I supposed to open the terminal app and paste this:
"./wpress_extractor /Users/cisco/Desktop/e/backup.wpress" ?

All I see is the "No such file or directory" message

Can some please tell me in simple step by step instructions how to open this on a Mac?

**Comment by fifthsegment** [comment]
You could just move the wpress_extractor to the directory which contains the backup.wpress file then simply run the extractor in a terminal with ./wpress_extractor backup.wpress

**Comment by contreras2004** [comment]
just drag and drop the files into the terinal. First drag wpress_extractor.dms to the terminal and after that drag the compressed file and press enter. It will start uncompressing the file in the same directory where the file wpress_extractor.dms is.

**Comment by dJunkyKode** [comment]
Thank you for the answers.. 
I ended up installing MAMP locally and importing the .wpress file. 
After that I went to the "htdocs" folder and got the files I needed.
