### ISSUE TITLE
Showing Not Compatible With My Windows Verison

### ISSUE THREAD

**Issue by arnabques** [fifthsegment/Wpress-Extractor#2]
Please let me know what's system requirements needed to run Wpress-Extractor. Mine is Windows 7.

**Comment by fifthsegment** [comment]
runs fine on Windows 7/8/8.1/10

**Comment by manusharma1** [comment]
Hi @fifthsegment 

I am getting this error : 

This version of C:\path\2\dir\wpress-extractor.exe is not compatible
 with the version of Windows you're running. Check your computer's system inform
ation to see whether you need a x86 (32-bit) or x64 (64-bit) version of the prog
ram, and then contact the software publisher.

What should I do now?

Thanks and Best Regards,
Manu

**Comment by OldGrumpy-de** [comment]
@manusharma1 
The downloadable executable is an x64 binary that only runs on 64-bit Windows. You'll need to compile a 32-bit version yourself I guess. Just for the records, I guess everybody runs x64 today.
