### ISSUE TITLE
Mac -bash: wpress_extractor: command not found

### ISSUE THREAD

**Issue by antonk52** [fifthsegment/Wpress-Extractor#4]
Downloaded the raw `wpress_extractor` file and placed it in `sen` folder, also placed my backup.wpress file in the same folder, cd'ed into the folder and ran `cmod +x wpress_extracor`, now the file is executable, now when I run `wpress_extractor backup.wpress` I get `-bash: wpress_extractor: command not found`

**Comment by fifthsegment** [comment]
run it as `./wpress_extractor backup.wpress`

**Comment by antonk52** [comment]
Thank you, worked great
Perhaps changing it in the readme can be helpful for future users

**Comment by able2create** [comment]
Hi, if I do that it tells me "no such file or directory"...
